name: Build releases

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如 1.0.0)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
      - name: Fetch code
        uses: actions/checkout@v4

      - name: Add build environment
        uses: Pathoschild/SMAPI-ModBuildWorkflow/add-build-environment@v1

      - name: Build mods
        run: dotnet build --configuration Release

      - name: Upload release zips
        uses: Pathoschild/SMAPI-ModBuildWorkflow/upload-release-artifacts@v1
        with:
          create_attestations: true
          create_combined_zip: "StardewMods"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          files: 'releases/*.zip'
          generate_release_notes: true
